In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2],[3, 4]]
tensor_data = torch.tensor(data)
tensor_data

tensor([[1, 2],
        [3, 4]])

In [3]:
array = np.array(data)
tensor_from_np = torch.from_numpy(array)
tensor_from_np

tensor([[1, 2],
        [3, 4]])

In [4]:
tensor_one = torch.ones_like(tensor_data)
tensor_rd = torch.rand_like(tensor_data, dtype=torch.float)
tensor_one, tensor_rd

(tensor([[1, 1],
         [1, 1]]),
 tensor([[0.0967, 0.0129],
         [0.7864, 0.5196]]))

In [6]:
shape = (3,4,)
torch.zeros(shape), torch.ones(shape), torch.rand(shape)

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[0.5047, 0.9350, 0.1998, 0.7971],
         [0.4294, 0.8615, 0.7691, 0.3809],
         [0.4488, 0.2268, 0.9650, 0.0052]]))

In [9]:
torch.cat([tensor_one, tensor_one, tensor_one])

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]])

In [10]:
torch.cat([tensor_one, tensor_one, tensor_one], dim=1)

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])

In [17]:
torch.ones(shape) @ torch.ones(shape).T, torch.ones(shape) * torch.ones(shape)

(tensor([[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [21]:
tensor_data.sum(), tensor_data.sum().item()

(tensor(10), 10)